name: CI
on:
  push:
    branches: 
      -  "master" 
jobs:
  docker: 
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
      - name: Docker Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: jyldyz0610/tetris-app:latest

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$AWS_SECRET_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          cat >>~/.ssh/config <<END
          Host 3.79.167.119
            HostName $SSH_KNOWN_HOSTS
            User $SSH_USER
            IdentityFile ~/.ssh/private.key
            StrictHostKeyChecking no
          END
        shell: bash
        env:
          AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
          SSH_KNOWN_HOSTS: 3.79.167.119
          SSH_USER: ec2-user

      - name: SSH into EC2 and Run Docker Container
        run: ssh ec2-user@3.79.167.119 "touch /tmp/action"
