name: CI
on:
  push:
    tags: 
      -  "v*" 
jobs:
  docker: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
      - name: Docker Build and Push
        uses: docker/build-push-action@v5
        with:
          images: jyldyz0610/tetris-app:latest
          tags:
            type=server,pattern={{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          contex: .
          file: ./Dockerfile
          push: true
          tags: ${{ strp.meta.outputs.tags }}
          labels: ${{ step.meta.outputs.labels }}
